# Generated by Django 2.2.6 on 2019-10-16 13:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20191016_1252'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('custom_comment', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_time', models.DateTimeField(auto_now=True, verbose_name='评论时间')),
                ('comment_content', models.TextField(verbose_name='内容简要')),
                ('comment_blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Blog', verbose_name='评论博客')),
                ('comment_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='评论用户')),
            ],
            options={
                'verbose_name': '评论',
                'verbose_name_plural': '评论',
                'ordering': ('-comment_time',),
            },
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
