# Generated by Django 2.2.6 on 2019-10-16 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20191012_1940'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='update_time',
            field=models.DateTimeField(verbose_name='更新时间'),
        ),
    ]
